{{ config(materialized='semantic_view') }}
	tables (
		{{ ref('orders') }} comment='The table contains records of customer orders placed at stores. Each record represents a single order and includes details about the customer, timing information, order status, and financial amounts, as well as delivery timeframes.',
		{{ ref('customers') }} primary key (CUSTOMER_ID) comment='The table contains records of customers and their associated contact information and order history metrics. Each record represents a single customer and includes personal details, satisfaction feedback, and aggregated order statistics across various time periods including delivery performance measures.'
	)
	relationships (
		ORDERS_TO_CUSTOMERS as ORDERS(CUSTOMER_ID) references CUSTOMERS(CUSTOMER_ID)
	)
	facts (
		ORDERS.TOTAL_AMOUNT as TOTAL_AMOUNT comment='The total amount of the order.'
	)
	dimensions (
		ORDERS.CUSTOMER_ID as CUSTOMER_ID comment='The unique identifier for the customer who placed the order.',
		ORDERS.DELIVERY_TIME_FROM_COLLECTION as DELIVERY_TIME_FROM_COLLECTION comment='The time duration between collection and delivery measured in a numeric unit.',
		ORDERS.DELIVERY_TIME_FROM_ORDER as DELIVERY_TIME_FROM_ORDER comment='The number of time units elapsed between order placement and delivery.',
		ORDERS.ORDER_ID as ORDER_ID comment='Unique identifier for each order in the system.',
		ORDERS.ORDER_STATUS as ORDER_STATUS comment='The current status of the order in its fulfillment lifecycle.',
		ORDERS.STORE_ID as STORE_ID comment='The identifier for the store where the order was placed.',
		ORDERS.ORDERED_AT as ORDERED_AT comment='The date and time when the order was placed.',
		CUSTOMERS.CUSTOMER_ID as CUSTOMER_ID comment='Unique identifier for each customer.',
		CUSTOMERS.EMAIL as EMAIL comment='Customer email addresses.',
		CUSTOMERS.FIRST_NAME as FIRST_NAME comment='The first name of the customer.',
		CUSTOMERS.LAST_NAME as LAST_NAME comment='Customer last names.'
	)
	metrics (
		ORDERS.REVENUE as sum(total_amount) with synonyms=('sales') comment='Revenue is the sum of total_amount. Some team members also call it sales. When we refer to a year, we mean our fiscal year which starts in October.'
	)
	comment='Sales analysis'
	ai_sql_generation 'When we refer to a year, we mean our fiscal year which starts in October.'
	with extension (ca='{"tables":[{"name":"ORDERS","dimensions":[{"name":"CUSTOMER_ID","sample_values":["15","63","14"]},{"name":"DELIVERY_TIME_FROM_COLLECTION","sample_values":["75","5"]},{"name":"DELIVERY_TIME_FROM_ORDER","sample_values":["150","30"]},{"name":"ORDER_ID","sample_values":["600cb823-092f-4112-a655-e5e1b6fbaf0e","d9702bf5-626b-4174-a005-b324ac0e851b","0103c3a8-2c82-4125-917a-b8a313fb5793"]},{"name":"ORDER_STATUS","sample_values":["ordered","delivered","pending"]},{"name":"STORE_ID","sample_values":["1"]}],"facts":[{"name":"TOTAL_AMOUNT","sample_values":["51.63","27.88","45.51"]}],"metrics":[{"name":"revenue"}],"time_dimensions":[{"name":"ORDERED_AT","sample_values":["2025-06-03T00:00:00.000+0000","2025-06-27T00:00:00.000+0000","2025-03-02T00:00:00.000+0000"]}]},{"name":"CUSTOMERS","dimensions":[{"name":"CUSTOMER_ID","sample_values":["27","34","67"]},{"name":"EMAIL","sample_values":["sienna.lopez@yahoo.com","julian.baxx@gmail.com","cyndi.root@gmail.com"]},{"name":"FIRST_NAME","sample_values":["Amalea","Sienna","Cordula"]},{"name":"LAST_NAME","sample_values":["Bromley","Lopez","Treat"]}]}],"relationships":[{"name":"ORDERS_TO_CUSTOMERS","relationship_type":"many_to_one","join_type":"inner"}],"verified_queries":[{"name":"0;1","sql":"SELECT o.order_id /* order facts */, o.ordered_at, o.order_status, o.total_amount, o.store_id, o.delivery_time_from_order, o.delivery_time_from_collection, c.customer_id /* customer dimension */, c.first_name, c.last_name, c.email FROM orders AS o INNER JOIN customers AS c ON o.customer_id = c.customer_id","question":"What are the complete order details combined with customer information?","verified_at":1772032298,"verified_by":"Semantic Model Generator"},{"name":"Who are the top 5 customers based on sales in 2026?","sql":"SELECT\\n  *\\nFROM\\n  SEMANTIC_VIEW(\\n    BREAKOUT_LABS.DBT_JBRAS.SALES_ANALYSIS METRICS revenue DIMENSIONS customers.customer_id,\\n    first_name,\\n    last_name\\n    WHERE\\n      ordered_at >= ''2025-10-01''\\n      AND ordered_at < ''2026-10-01''\\n  )\\nORDER BY\\n  revenue DESC NULLS LAST\\nLIMIT\\n  5\\n  /* Generated by Cortex Analyst (request_id: 247b2449-178d-40b7-b15f-acebfe202771) */","question":"Who are the top 5 customers based on sales in 2026?","verified_at":1772032900,"verified_by":"JOAO_BRAS","use_as_onboarding_question":false}]}')